---
- name: ensure zsh configuration is added to stack.d
  copy: src=node.zsh dest={{ stack_d }}

- name: ensure nvm is installed/updated to HEAD
  homebrew: name=nvm state=head

- name: ensure node versions are installed
  shell: source $(brew --prefix nvm)/nvm.sh && nvm install {{ item }}
  with_items:
    - stable
    - iojs
  register: nvm_install_result
  changed_when: "'already installed' not in nvm_install_result.stderr"

- name: ensure configuration is added to stack.d
  copy: src={{ item }} dest={{ stack_d }}
  with_items:
    - node.bundle
    - node.vimrc.before
  notify: vim bundle install
